# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template and provide as much information as possible.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines and make sure your PR follows them.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! We appreciate your contribution!

# Configuration for request-info - https://github.com/behaviorbot/request-info

# *Required* Comment to reply with
requestInfoReplyComment: >
  We would appreciate it if you could provide more information about this issue/PR.

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info

# Configuration for sentiment-bot - https://github.com/behaviorbot/sentiment-bot

# *Required* Comment to reply with
sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users.

# When a comment contains words matching the regex below, the comment will be marked as toxic and a comment will be posted.
sentimentBotToxicityThreshold: .7

# Comment to post when a toxic comment is posted
sentimentBotReplyComment: >
  Please be sure to review our code of conduct and be respectful of other users.
